/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.fruitful.ecomerce;

import io.fruitful.ecomerce.commons.MagentoException;
import io.fruitful.ecomerce.dto.BaseCustomerTokenRequest;
import io.fruitful.ecomerce.dto.MagentoProductResponse;
import io.fruitful.ecomerce.dto.MagentoProductSearchRequest;
import io.fruitful.ecomerce.magento.MagentoAdmin;
import io.fruitful.ecomerce.magento.MagentoCustomer;
import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() throws MagentoException {
//        Configuration configuration = new Configuration();
//        configuration.setEndpoint("https://test.omnyfy.cliquefan.com");
//        configuration.setIntegrationToken("");
//        configuration.setMediaLocation("");
//        MagentoFactory magentoFactory = new MagentoFactory(configuration);
//
//        // call using integrationToken
//        MagentoAdmin admin = magentoFactory.getInstance();
//        MagentoProductSearchRequest request = new MagentoProductSearchRequest();
//        MagentoProductResponse magentoProductResponse = admin.searchProduct(null, request);
//
//        // call using customerToken
//        String customerToken = "";
//        MagentoCustomer customer = magentoFactory.getInstance(customerToken);
//        String cartId = customer.createCart();
    }
}
